---
title: "Hydrofabric Data Model and Alignment"
author: "Mike Johnson"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dm)
library(DBI)
library(sf)
```

```{r, echo = FALSE}

hf = list(
lookup_table = data.frame(
  id         = integer(1L),
  hf_source  = integer(1),
  hf_id      = numeric(1L),
  hf_id_part = integer(1L),
  mainstem   = integer(1L),
  poi_id     = integer(1L),
  poi_type   = integer(1L),
  poi_value  = integer(1L),
  wb_id      = integer(1L),
  divide_id  = integer(1L)
),

flowlines = data.frame(
  id = integer(1L),
  toid = integer(1L),
  mainstem = integer(1L),
  lengthkm = numeric(1L),
  tot_drainage_areasqkm = numeric(1L),
  #slope = numeric(1L),
  order = numeric(1L),
  hydroseq = numeric(1L),
  areasqkm = numeric(1L),
  #gnis_id = numeric(1L),
  #gnis_name = numeric(1L),
  divide_id = integer(1L),
  geometry = numeric(1L),
  has_divide = logical(1)
),


POIs = data.frame(
  poi_id = integer(1L),
  id     = integer(1L),
  geometry = numeric(1L)
),

divides = data.frame(
  divide_id = integer(1L),
  id   = integer(1L),
  toid = integer(1L),
  areasqkm = numeric(1L),
  network_type = character(1L),
  geometry = numeric(1L),
  has_flowline = logical(1)
),

network = data.frame(
  id = integer(1L),
  toid = integer(1L),
  divide_id = integer(1L),
  wb_id = integer(1L),
  poi_id = integer(1L),
  lengthkm = numeric(1L),
  areasqkm = numeric(1L),
  tot_drainage_areasqkm = numeric(1L),
  mainstem = numeric(1L),
  has_flowline = logical(1),
  has_divide = logical(1),
  network_type = character(1L)
),

WB = data.frame(
  wb_id = integer(1L),
  #gnis_id = numeric(1L),
  #gnis_name = character(1L),
  wb_area = numeric(1L),
  wb_source = numeric(1L),
  geometry = numeric(1L)
)
)

meta = tibble::tribble(
~Attribute, ~Description,
"id",             "A hydrofabric specfic, globaly unique flowpath/flowline identifier",
"hf_source",      "Unique Integer Indentifer for Hydrofabric Origin",
"hf_id",          "The origin hydrofabric identifier",
"hf_id_part",     "If the original hydrofabric identifierwas split, the subpart. Parts increase from outlet to inlet",
"divide_id",      "A hydrofabric specfic, globaly unique divide identifier",
"mainstem",       "the primary downstream segment of a river, as contrasted to its tributaries",
"poi_id",         "A hydrofabric specifc, globaly unique Point of Interest identifier",
"poi_type",       "The Point of Interest type",
"poi_value",      "The origional identifier of the POI in the native dataset",
"wb_id",          "Water body Common Identifier from wb_source",


"toid",                     "The identifier of the directly downstream flowpath/flowline",
"lengthkm",                 "The length in kilometers of the flowpath element",
"areasqkm",                 "The area of the incremental divide for a given flowpath/flowline",
"tot_drainage_areasqkm",    "The total upstream area contributing to the flowpath/flowline",

"order",                    "Strahler stream order",
"hydroseq",                 "VPU based hydrologic sort. Increases from downstream to upstream",

"geometry",      "Simple Features Geometry",
"network_type",  "Type of network feature (network, internal, coastal, connector), previously was divide_type",

"wb_area",       "Waterbody area",
"wb_source",     "Waterbody source",

"has_divide",    "Does an abstract catchment have a divide realization",
"has_flowline",  "Does an abstract catchment have a flowline/flowpath realization")


dm = dm::dm(lookup_table = hf$lookup_table,
            flowlines = hf$flowlines,
            POIs = hf$POIs,
            divides = hf$divides,
            network = hf$network,
            WB = hf$WB) %>% 

  dm_add_pk(flowlines, id)  %>% 
  dm_add_pk(POIs, poi_id)  %>% 
  dm_add_pk(WB, wb_id)  %>% 
  dm_add_pk(divides, divide_id)  %>% 
  dm_set_colors(red = flowlines, 
                red = divides,
                gray = lookup_table, 
                red = POIs,
                red = WB, 
                gray = network)


df = data.frame(names = names(unlist(hf))) %>% 
             tidyr::separate(names, sep = "[.]", into  = c('layer', 'Attribute')) %>% 
  group_by(Attribute) %>% 
  summarise(layers = paste(layer, collapse = ", "))


meta = left_join(meta, df, by = "Attribute")

```


## Proposed Data Model (`r Sys.Date()`)

### `red`: spatial
### `gray`: tabular

<br><br><br>

```{r, echo = FALSE, fig.height=8, fig.width=8, fig.show='hold'}
dm_draw(dm,  view_type = "all", column_types = TRUE, rankdir = "LR")
```

```{r, echo = FALSE}
DT::datatable(meta, options = list(pageLength = 35, dom = 't'), rownames = FALSE)
```